import CompanyHome from "@/component/CompanyHome"
import NavBar from "@/component/Navbar"
import Head from 'next/head'
function CompanyHomePage() {
    return <>
    <NavBar/>
    <Head>
        <title>3d Printing Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <CompanyHome/>
    </>
  }
  
  export default CompanyHomePage