import Head from "next/head";
import { Inter } from "@next/font/google";
import { HomePage } from "@/component/landing_page/home";
import NavBar from "@/component/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <NavBar />
      <Head>
        <title>3d Printing Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
